# ブラウザ設定ファイル
# browser-useライブラリのBrowserConfigに関する設定を管理

browser:
  # 基本設定
  headless: false                    # ヘッドレスモード（true: 非表示、false: ブラウザ表示）
  save_recording_path: ./tmp/my_recording  # 録画データの保存パスを指定（nullの場合は保存しない）

  # パフォーマンス設定
  window_width: 1920               # ブラウザウィンドウの幅
  window_height: 1080              # ブラウザウィンドウの高さ

  # ネットワーク設定
  timeout: 30                      # ページ読み込みタイムアウト（秒）

# プロンプト設定選択
prompt_selection:
  # 使用するプロンプトテンプレート名を指定
  # prompt.yamlから該当するテンプレートを選択
  task_template: "meta_attendance_task_template"  # デフォルト使用テンプレート