# LLMプロンプト設定ファイル
# AIエージェントに与えるタスクプロンプトを定義

# AIエージェントが実行するデフォルトタスク
default_task: "勤怠管理システムにアクセスして、勤怠情報を確認してください"

# 勤怠管理システム用のタスク設定（環境変数を使用）
attendance_task_template: |
  {target_url}の勤怠管理システムにアクセスし、勤怠情報を確認してください：
  1. ログインページにアクセス
  2. Googleでログインボタンをクリック
  3. メールアドレスまたは電話番号に{login_email}を入力し次へをクリック
  4. パスワードに{login_password}を入力し確認を実行
  5. ログインしたアカウントが{expected_name}であることを確認。違う場合は終了する
  6. 勤怠ボタンをクリック
  7. 別のタブが開き打刻画面が表示される