# LLMプロンプト設定ファイル
# AIエージェントに与えるタスクプロンプトを定義

# AIエージェントが実行するデフォルトタスク
default_task: "勤怠管理システムにアクセスして、勤怠情報を確認してください"

# 勤怠管理システム用のタスク設定（環境変数を使用）
attendance_task_template: "{target_url}の勤怠管理システムにアクセスし、以下の手順で勤怠情報を確認してください：
  1. ログインページにアクセス
  2. ログイン情報を入力してログイン
  3. 勤怠情報のメニューまたはダッシュボードに移動
  4. 本日の出勤・退勤時刻を確認
  5. 今月の勤怠状況（出勤日数、労働時間等）を確認
  6. 必要に応じて勤怠の修正や申請状況を確認"